import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AuthListener from "@/features/auth/components/AuthListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout (Server Component)
 * -----------------------------
 * Es el componente de más alto nivel que define la estructura base del documento HTML.
 * Asegura que los estilos globales y el monitoreo de sesión estén presentes siempre.
 * * @param {React.ReactNode} children - Páginas y layouts anidados.
 * * @param {Promise} params - Parámetros de ruta para identificar al tenant.
 * * Datos:
 * - Configura las fuentes 'Geist' para una visualización moderna.
 * - Define metadatos globales para el SEO de la aplicación.
 * * * * Flujo:
 * 1. Resuelve el parámetro 'tenant' de forma asíncrona desde la URL.
 * 2. Define el esquema HTML y aplica las variables de fuente en el cuerpo del documento.
 * 3. Inyecta el 'AuthListener' para sincronizar la sesión en toda la aplicación.
 * 4. Despliega los componentes hijos dentro de la estructura principal.
 * * * * @return JSX.Element - El esqueleto fundamental de la aplicación.
 */
export default async function RootLayout({
  children, params
}: Readonly<{children: React.ReactNode, params: Promise<{ tenant: string }>;}>) {

  // 1.
  const { tenant } = await params;

  return (
    // 2.
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* 3. */}
      <AuthListener tenant = {tenant}/>
        
        {/* 4. */}
        {children}
      </body>
    </html>
  );
}